In [43]:
import numpy as np
import pandas as pd

In [ ]:
day = 4
input_file = f"inputs/day{day}input.text"
with open(input_file, 'r') as file:   

    characters = [list(char) for char in file.read().splitlines()]
    data = pd.DataFrame(characters)

data

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,A,S,A,M,X,S,M,X,M,A,...,A,M,A,S,M,X,M,A,S,M
1,M,M,X,X,A,M,X,A,X,S,...,S,X,A,M,A,A,A,S,A,S
2,S,A,M,M,A,X,M,S,M,X,...,A,M,S,S,S,X,M,X,A,X
3,A,A,M,S,A,M,M,A,M,A,...,M,M,A,A,A,M,M,M,S,M
4,M,M,M,S,A,X,S,M,X,M,...,X,M,M,S,M,A,A,A,M,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,M,X,M,A,A,S,A,S,M,S,...,M,S,M,X,X,M,X,M,M,M
136,A,X,A,S,X,M,A,X,X,X,...,X,A,A,S,M,M,A,S,A,M
137,M,A,X,X,S,M,M,M,M,S,...,A,A,S,M,A,S,A,S,A,S
138,X,M,S,A,M,X,A,A,M,A,...,A,M,X,X,X,M,X,S,M,M
139,A,X,M,X,M,S,S,S,S,M,...,A,X,S,A,M,X,X,M,A,S

In [ ]:
##solution 1
target = ['XMAS','SAMX']
total = 0
hvalue_count = dvalue_count = vvalue_count = odvalue_count = 0
i = 0
j = 0
rows = len(data)
columns = len(data.columns)
for row in range(rows):
    i = row
    for column in range(columns):
        j = column
        vvalue = ''.join(data[j][i:i+4])
        hvalue = ''.join(data.iloc[[j],i:i+4].agg(''.join, axis=1))
        dvalue = ''.join(pd.Series(np.diagonal(data.iloc[i:i+4,j:j+4])))
        odvalue = ''.join(pd.Series(np.diagonal(np.fliplr(data.iloc[i:i+4,j:j+4]))))
        if hvalue in target:
            hvalue_count += 1
        if vvalue in target:
            vvalue_count += 1
        if dvalue in target:
            dvalue_count +=1
        if odvalue in target:
            odvalue_count +=1

In [ ]:
##Solution 2
target = ['MAS','SAM']
total = 0
hvalue_count = dvalue_count = vvalue_count = odvalue_count = 0
i = 1
j = 1
rows = len(data)
columns = len(data.columns)
for row in range(1,rows-1):
    i = row
    for column in range(1,columns-1):
        j = column
        candidate = data.iloc[i,j]
        dvalue, odvalue = None, None
        if candidate == 'A':
            matrix = data.loc[i-1:i+1,j-1:j+1]
            dvalue = ''.join(pd.Series(np.diagonal(matrix)))
            odvalue = ''.join(pd.Series(np.diagonal(np.fliplr(matrix))))
        if set([dvalue,odvalue]) <= set(target):
            total += 1
total

In [251]:
total

2048